version: "2.4"
services:
  comet:
    image: txchat-comet:${COMET_IMAGE}
    container_name: ${COMET_CONTAINER_NAME}
    environment:
      ETCD_HOST: ${ETCD_CONTAINER_NAME}
    networks:
      - components
      - service
    volumes:
      - comet_config:/etc/comet/config
    ports:
      - "3101:3101"
      - "3102:3102"
      - "8000:8000"
    depends_on:
      - etcd
  logic:
    image: txchat-logic:${LOGIC_IMAGE}
    container_name: ${LOGIC_CONTAINER_NAME}
    environment:
      ETCD_HOST: ${ETCD_CONTAINER_NAME}
      REDIS_HOST: ${REDIS_CONTAINER_NAME}
      KAFKA_HOST: ${KAFKA_CONTAINER_NAME}
      CHAT_API_HOST: ${ECHO_CONTAINER_NAME}
    networks:
      - components
      - service
    volumes:
      - logic_config:/etc/logic/config
    depends_on:
      kafka:
        condition: service_healthy
      redis:
        condition: service_started
      comet:
        condition: service_started
      etcd:
        condition: service_started
  echo:
    image: txchat-echo:${ECHO_IMAGE}
    container_name: ${ECHO_CONTAINER_NAME}
    environment:
      ETCD_HOST: ${ETCD_CONTAINER_NAME}
      KAFKA_HOST: ${KAFKA_CONTAINER_NAME}
    networks:
      - components
      - service
    volumes:
      - echo_config:/etc/echo/config
    depends_on:
      kafka:
        condition: service_healthy
      redis:
        condition: service_started
      comet:
        condition: service_started
      logic:
        condition: service_started
      etcd:
        condition: service_started
networks:
  components:
    external: false
  service:
    external: false
volumes:
  comet_config:
    name: ${COMET_CONFIG_VOLUME}
    external: false
  logic_config:
    name: ${LOGIC_CONFIG_VOLUME}
    external: false
  echo_config:
    name: ${ECHO_CONFIG_VOLUME}
    external: false
