env="release"

[log]
    Level="info"
    Mode="console"
    Path=""
    Display="json"

[Trace]
    ServiceName=""
    Gen128Bit=true
[Trace.Sampler]
    Type="const"
    Param=1.0
[Trace.Reporter]
    LogSpans=true
    LocalAgentHostPort="txchat-jaeger:6831"

[reg]
    schema   = "im"
    srvName  = "comet"
    regAddrs = "txchat-etcd:2379"

[logicRPCClient]
    schema  = "im"
    srvName = "logic"
    dial    = "1s"
    timeout = "1s"

[RPCServer]
    Network                           = "tcp"
    Addr                              = ":3109"
    Timeout                           = "1s"
    KeepAliveMaxConnectionIdle        = "60s"
    KeepAliveMaxConnectionAge         = "2h"
    KeepAliveMaxMaxConnectionAgeGrace = "20s"
    KeepAliveTime                     = "60s"
    KeepAliveTimeout                  = "20s"

[tcp]
    bind         = [":3101"]
    sndbuf       = 4096
    rcvbuf       = 4096
    keepalive    = false
    reader       = 32
    readBuf      = 1024
    readBufSize  = 8192
    writer       = 32
    writeBuf     = 1024
    writeBufSize = 8192

[websocket]
    bind        = [":3102"]
    tlsOpen     = false
    tlsBind     = [":3103"]
    certFile    = "../../cert.pem"
    privateFile = "../../private.pem"

[protocol]
    timer            = 32
    timerSize        = 2048
    svrProto         = 10
    cliProto         = 5
    handshakeTimeout = "8s"
    minHeartbeat     = "5s"
    maxHeartbeat     = "10s"
    rto              = "2s"

[bucket]
    size    = 32
    channel = 1024